//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Areas.FoodArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int FoodID { get; set; }
        public string FoodName { get; set; }
        public Nullable<decimal> price { get; set; }
        public string RestaurantName { get; set; }
        public string Foodpicture { get; set; }
        public byte[] BytesImage { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Description { get; set; }
    
        public virtual FoodCategory FoodCategory { get; set; }
    }
}
